FROM ruby:3.3-slim

RUN apt-get update -qq && \
    apt-get install -y build-essential apt-utils libpq-dev nodejs && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /coxinha-toda-toda-api

ENV RAILS_ENV="staging" \
    BUNDLE_WITHOUT="development test"

RUN gem install bundler

COPY Gemfile* ./

RUN bundle install --full-index --jobs=$(nproc)

COPY . .

ENTRYPOINT ["/coxinha-toda-toda-api/bin/docker-entrypoint"]

CMD ["./bin/rails", "server", "-b", "0.0.0.0"]
