services:
  db:
    image: 'postgres:latest'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword

  rails:
    build: ./
    ports:
      - '3000:3000'
    volumes:
      - .:/coxinha-toda-toda-api
    depends_on:
      - db

volumes:
  postgres:
