default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: mysecretpassword
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: coxinha_toda_toda_development

test:
  <<: *default
  database: coxinha_toda_toda_test
