default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: mysecretpassword
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: coxinha_toda_toda_development

test:
  <<: *default
  database: coxinha_toda_toda_test

staging:
  <<: *default
  database: <%= ENV['STAGING_DB_NAME'] %>
  host: <%= ENV['STAGING_DB_HOST'] %>
  username: <%= ENV['STAGING_DB_USERNAME'] %>
  password: <%= ENV['STAGING_DB_PASSWORD'] %>
