default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: mysecretpassword
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: coxinha_toda_toda_development

test:
  <<: *default
  database: coxinha_toda_toda_test

production:
  <<: *default
  database: coxinha_toda_toda_production
  username: <%= ENV['PROD_DB_USERNAME'] %>
  password: <%= ENV['PROD_DB_PASSWORD'] %>

staging:
  <<: *default
  database: coxinha_toda_toda_staging
  username: <%= ENV['STAGING_DB_USERNAME'] %>
  password: <%= ENV['STAGING_DB_PASSWORD'] %>
